name = "clear-steel"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改

id = "ba2478c35ab34b8c8f4e8954db09ab53"				#KV数据库id

